name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  code: 
    runs-on: ubuntu-latest
    steps:
        - name: code checkout
          uses: actions/checkout@v4
        
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Code Build with docker
          run: echo Hello, world!
          
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test done successfully

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Code Deploy
        run: echo "Code deploy done"
